### PR TITLE
Fixes compilation errors and implements general improvements

### PR DESCRIPTION
**Pull request by johnoro**
The listed problems below are in order with the commits that fix them. 
Note that these problems occurred on [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) and that these fixes were only tested on the same system.
- In [pointers/pointers.c](https://github.com/LambdaSchool/Intro-to-C/blob/master/pointers/pointers.c#L50), some of the strings in the main function are missing quotes, causing a compilation error out of the box.
- In [mainbuild.mk](https://github.com/LambdaSchool/Intro-to-C/blob/master/mainbuild.mk#L5), object files are being compiled with no extension. Assuming this isn't somehow system-dependent, then this change should happen so that these files aren't put in version control (when they are, it creates bloat for PMs and slows down pushes for the students).
- In [structs/lib.h](https://github.com/LambdaSchool/Intro-to-C/blob/master/structs/lib.h#L8), `strdup`'s function header is being assumed wrong due to the `-std=c99` flag used in the [mainbuild.mk](https://github.com/LambdaSchool/Intro-to-C/blob/master/mainbuild.mk#L5) file. This causes a runtime error, which doesn't allow students to successfully run their object code even with correct implementations. The problem is more thoroughly explained [here](https://stackoverflow.com/a/26284172/11186034).
- In [queue/lib.h](https://github.com/LambdaSchool/Intro-to-C/blob/master/queue/lib.h), an unnecessary, unused parameter is in `resize_memory`. It seems to only be confusing to abstract something away with misleading parameters.
- In [quicksort/quicksort.c](https://github.com/LambdaSchool/Intro-to-C/blob/master/quicksort/quicksort.c#L5), a `swap` function that has already been implemented is mentioned, but there is not a `swap` function to implement in the [pointers module](https://github.com/LambdaSchool/Intro-to-C/blob/master/pointers/pointers.c) currently.

The next commit is simply for merging the updates to the README into this branch.

- In [pointers/pointers.h](https://github.com/LambdaSchool/Intro-to-C/blob/master/pointers/pointers.h), there are a few unused function declarations. This could be potentially misleading/confusing.
- In [pointers/tests/pointers_tests.c](https://github.com/LambdaSchool/Intro-to-C/blob/master/pointers/tests/pointers_tests.c), the string copy test is never run. I assume this was just missed/forgotten about.

### CODE REVIEW

**Comment by beejjorgensen** [comment]
Cherry-picked most of these, with a couple exceptions:

`mainbuild.mk` was left as-is, since that build product is an executable, not an object file. Instead, added the Unix executable names to `.gitignore`.

Unused prototypes in `pointers.h` were left as-is, since they tend to get used by students for implementation.

Thanks for the help!

**Comment by johnoro** [comment]
Awesome, thank you!

**Comment by johnoro** [comment]
Do you think just replacing my `.o` with `.exe` for the second solution might be appropriate? It'd probably be best to have something that won't have to be added onto in the future in case any modules are added or renamed. `.exe` files are also already in the .gitignore @beejjorgensen

**Comment by beejjorgensen** [comment]
In spirit, yes, that would be sensible.

But `.exe` extensions in Unix aren't idiomatic. It would look really weird to Unix/Mac users. And they'd have to type `malloc.exe` to run the thing instead of just `malloc`.

**Comment by johnoro** [comment]
One last thing; for the line ending problem that's unique to window users (bash shell scripts, `.sh` files, 'barfing' when line endings are converted to CRLF from LF), do you think a `.gitattributes` would work for that? For example: https://github.com/johnoro/Intro-to-C/blob/project/.gitattributes
It seemed to work pretty well on my machine, but I'm not entirely sure if it works as expected (that being, it should stop line ending conversions) when pulling or not. [This](https://help.github.com/en/articles/dealing-with-line-endings#per-repository-settings) is where I got the idea from.

**Pull request closed without merging**
